export interface Question {
  id: number;
  category: 'Mindset & Thinking' | 'Personality & Behaviour' | 'Motivation & Goals' | 'Emotional & Lifestyle Patterns';
  categoryIcon: string;
  categoryEmoji: string;
  question: string;
  options: string[];
}

export const ASSESSMENT_QUESTIONS: Question[] = [
  {
    id: 1,
    category: 'Mindset & Thinking',
    categoryIcon: 'brain',
    categoryEmoji: '🧠',
    question: 'Your thought process?',
    options: ['Optimistic', 'Pessimistic', 'Realistic', 'Overthinking'],
  },
  {
    id: 2,
    category: 'Mindset & Thinking',
    categoryIcon: 'brain',
    categoryEmoji: '🧠',
    question: 'Your decision-making style?',
    options: ['Logical', 'Emotional', 'Intuitive', 'Analytical'],
  },
  {
    id: 3,
    category: 'Personality & Behaviour',
    categoryIcon: 'leaf',
    categoryEmoji: '🌿',
    question: 'Your personality?',
    options: ['Introvert', 'Extrovert', 'Ambivert', 'Reserved'],
  },
  {
    id: 4,
    category: 'Motivation & Goals',
    categoryIcon: 'fire',
    categoryEmoji: '🔥',
    question: 'Your biggest motivation?',
    options: ['Success', 'Money', 'Recognition', 'Happiness'],
  },
  {
    id: 5,
    category: 'Emotional & Lifestyle Patterns',
    categoryIcon: 'heart',
    categoryEmoji: '💜',
    question: 'Your biggest fear?',
    options: ['Failure', 'Rejection', 'Loss', 'Uncertainty'],
  },
  {
    id: 6,
    category: 'Emotional & Lifestyle Patterns',
    categoryIcon: 'heart',
    categoryEmoji: '💜',
    question: 'When stressed, you become?',
    options: ['Quiet', 'Emotional', 'Angry', 'Practical'],
  },
  {
    id: 7,
    category: 'Personality & Behaviour',
    categoryIcon: 'leaf',
    categoryEmoji: '🌿',
    question: 'Your communication style?',
    options: ['Direct', 'Diplomatic', 'Reserved', 'Expressive'],
  },
  {
    id: 8,
    category: 'Mindset & Thinking',
    categoryIcon: 'brain',
    categoryEmoji: '🧠',
    question: 'Your approach towards problems?',
    options: ['Solve immediately', 'Analyse deeply', 'Ask for help', 'Avoid temporarily'],
  },
  {
    id: 9,
    category: 'Personality & Behaviour',
    categoryIcon: 'leaf',
    categoryEmoji: '🌿',
    question: 'Your attitude towards change?',
    options: ['Excited', 'Cautious', 'Resistant', 'Adaptive'],
  },
  {
    id: 10,
    category: 'Mindset & Thinking',
    categoryIcon: 'brain',
    categoryEmoji: '🧠',
    question: 'You trust more?',
    options: ['Logic', 'Feelings', 'Experience', 'Other people\'s advice'],
  },
  {
    id: 11,
    category: 'Emotional & Lifestyle Patterns',
    categoryIcon: 'heart',
    categoryEmoji: '💜',
    question: 'Your lifestyle preference?',
    options: ['Planned', 'Spontaneous', 'Balanced', 'Flexible'],
  },
  {
    id: 12,
    category: 'Personality & Behaviour',
    categoryIcon: 'leaf',
    categoryEmoji: '🌿',
    question: 'In a group, you are usually?',
    options: ['Leader', 'Observer', 'Contributor', 'Supporter'],
  },
  {
    id: 13,
    category: 'Motivation & Goals',
    categoryIcon: 'fire',
    categoryEmoji: '🔥',
    question: 'What matters most to you?',
    options: ['Freedom', 'Security', 'Relationships', 'Achievement'],
  },
  {
    id: 14,
    category: 'Emotional & Lifestyle Patterns',
    categoryIcon: 'heart',
    categoryEmoji: '💜',
    question: 'When criticized, you feel?',
    options: ['Defensive', 'Hurt', 'Curious', 'Unaffected'],
  },
  {
    id: 15,
    category: 'Personality & Behaviour',
    categoryIcon: 'leaf',
    categoryEmoji: '🌿',
    question: 'Your energy comes from?',
    options: ['Being alone', 'Being with people', 'Achieving goals', 'Trying new things'],
  },
  {
    id: 16,
    category: 'Mindset & Thinking',
    categoryIcon: 'brain',
    categoryEmoji: '🧠',
    question: 'You focus more on?',
    options: ['Past', 'Present', 'Future', 'All equally'],
  },
  {
    id: 17,
    category: 'Emotional & Lifestyle Patterns',
    categoryIcon: 'heart',
    categoryEmoji: '💜',
    question: 'Your risk-taking nature?',
    options: ['High', 'Moderate', 'Low', 'Situation-based'],
  },
  {
    id: 18,
    category: 'Personality & Behaviour',
    categoryIcon: 'leaf',
    categoryEmoji: '🌿',
    question: 'You are more?',
    options: ['Competitive', 'Cooperative', 'Independent', 'Balanced'],
  },
  {
    id: 19,
    category: 'Emotional & Lifestyle Patterns',
    categoryIcon: 'heart',
    categoryEmoji: '💜',
    question: 'Your emotional expression?',
    options: ['Open', 'Controlled', 'Hidden', 'Situational'],
  },
  {
    id: 20,
    category: 'Motivation & Goals',
    categoryIcon: 'fire',
    categoryEmoji: '🔥',
    question: 'You prefer?',
    options: ['Stability', 'Adventure', 'Growth', 'Comfort'],
  },
];
